# Server Deploying
BASE_URL = ''

# SMTP Service
SMTP_SENDER_NAME = ''
SMTP_SENDER_EMAIL = ''
SMTP_USE_SSL = True
SMTP_SERVER_URL = ''
SMTP_SERVER_PORT = ''
SMTP_ACCOUNT_USERNAME = ''
SMTP_ACCOUNT_PASSWORD = ''

# Linebot
LINEBOT_CHANNEL_ACCESS_TOKEN = ''
LINEBOT_CHANNEL_SECRET = ''

# Google Map API
GOOGLE_CLOUD_API_KEY = ''
